/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LocationPin: typeof import('./../components/markers/LocationPin.vue')['default']
    MiniMap: typeof import('./../components/mini-map/MiniMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleMarker: typeof import('./../components/markers/SimpleMarker.vue')['default']
  }
}
