/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./../components/SimpleMarker copy.vue')['default']
    LocationPin: typeof import('./../components/LocationPin.vue')['default']
    Map: typeof import('./../components/Map.vue')['default']
    MapMarker: typeof import('./../components/MapMarker.vue')['default']
    MiniMap: typeof import('./../components/MiniMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCard: typeof import('./../components/SettingsCard.vue')['default']
    SimpleMarker: typeof import('./../components/SimpleMarker.vue')['default']
    VuetifyMapMarker: typeof import('./../components/VuetifyMapMarker.vue')['default']
  }
}
